/**
 * ข้อมูลรีวิวโบรกเกอร์ Forex 50 อันดับ
 * อ้างอิงอันดับความนิยม/เรตติ้งจากแหล่งข้อมูลรีวิวไทย + เรียบเรียงสเปกใหม่
 * ⚠️ ข้อมูลอาจเปลี่ยนแปลง โปรดตรวจสอบกับโบรกเกอร์โดยตรงก่อนตัดสินใจ
 */
export type Broker = {
  rank: number;
  name: string;
  slug: string;
  rating: number; // 1–5
  leverage: string;
  minDeposit: string;
  regulation: string;
  type: string;
  platforms: string;
  highlight: string;
  pros: string[];
  cons: string[];
};

export const BROKERS: Broker[] = [
  { rank: 1, name: "Exness", slug: "exness", rating: 5, leverage: "1:ไม่จำกัด", minDeposit: "$10", regulation: "FCA, CySEC, FSCA, FSA", type: "Hybrid", platforms: "MT4 / MT5 / App", highlight: "เจ้าตลาดในไทย ถอนเงินอัตโนมัติไวมาก สเปรดต่ำ เลเวอเรจไม่จำกัด", pros: ["ฝาก-ถอนอัตโนมัติ เร็วที่สุดในตลาด", "สเปรดต่ำ มีบัญชี Zero/Raw", "เลเวอเรจไม่จำกัด เปิดบัญชีง่าย"], cons: ["ไม่มีใบอนุญาตระดับ Tier-1 หลายใบเท่าเจ้าใหญ่ EU"] },
  { rank: 2, name: "Eightcap", slug: "eightcap", rating: 4, leverage: "1:500", minDeposit: "$100", regulation: "ASIC, FCA, CySEC, SCB", type: "Hybrid", platforms: "MT4 / MT5 / TradingView", highlight: "เชื่อมต่อ TradingView ตรง เหมาะสายเทรดคริปโตและ CFD", pros: ["รวม TradingView ใช้งานง่าย", "สเปรดแข่งขันได้ มีบัญชี Raw"], cons: ["เงินฝากขั้นต่ำสูงกว่าเจ้าอื่นบางราย"] },
  { rank: 3, name: "Tickmill", slug: "tickmill", rating: 4, leverage: "1:1000", minDeposit: "$100", regulation: "FCA, CySEC, FSA, FSCA", type: "Hybrid", platforms: "MT4 / MT5", highlight: "ค่าคอมต่ำ บัญชี Pro สเปรดเริ่ม 0.0 เหมาะ Scalping", pros: ["ค่าคอมมิชชันต่ำ", "กำกับดูแลหลายประเทศ น่าเชื่อถือ"], cons: ["โปรโมชันน้อยกว่าเจ้าอื่น"] },
  { rank: 4, name: "FxPro", slug: "fxpro", rating: 4, leverage: "1:ไม่จำกัด", minDeposit: "$100", regulation: "FCA, CySEC, FSCA, SCB", type: "Hybrid", platforms: "MT4 / MT5 / cTrader", highlight: "โบรกเก่าแก่ มี cTrader ครบ เหมาะเทรดเดอร์มืออาชีพ", pros: ["รองรับ cTrader เต็มรูปแบบ", "ชื่อเสียงยาวนาน กำกับดูแลดี"], cons: ["สเปรดบัญชีมาตรฐานสูงกว่าบัญชี Raw"] },
  { rank: 5, name: "Pepperstone", slug: "pepperstone", rating: 5, leverage: "1:500", minDeposit: "ไม่กำหนด", regulation: "ASIC, FCA, CySEC, DFSA, SCB", type: "A-book", platforms: "MT4 / MT5 / cTrader / TradingView", highlight: "A-book แท้ ส่งคำสั่งไว สเปรดต่ำมาก กำกับดูแลแน่น", pros: ["A-book โปร่งใส ไม่สวนเทรด", "สเปรดต่ำ ส่งคำสั่งเร็ว", "ใบอนุญาต Tier-1 หลายใบ"], cons: ["ไม่มีโบนัสเงินฝาก"] },
  { rank: 6, name: "HFM (HotForex)", slug: "hfm", rating: 4, leverage: "1:2000", minDeposit: "$0", regulation: "CySEC, FCA, FSCA, DFSA", type: "Hybrid", platforms: "MT4 / MT5", highlight: "บัญชี Cent + Free Swap เหมาะมือใหม่ทุนน้อย", pros: ["มีบัญชี Cent ทดลองทุนจริงน้อย", "โบนัสและโปรโมชันเยอะ"], cons: ["สเปรดบัญชีพื้นฐานปานกลาง"] },
  { rank: 7, name: "IC Markets", slug: "ic-markets", rating: 4, leverage: "1:1000", minDeposit: "$200", regulation: "ASIC, CySEC, FSA", type: "A-book / ECN", platforms: "MT4 / MT5 / cTrader", highlight: "ECN สเปรดต่ำสุด ๆ ขวัญใจสาย Scalping/EA", pros: ["ECN สเปรดเริ่ม 0.0 จริง", "สภาพคล่องสูง เหมาะรัน EA"], cons: ["เงินฝากขั้นต่ำ $200"] },
  { rank: 8, name: "FBS", slug: "fbs", rating: 3, leverage: "1:3000", minDeposit: "$5", regulation: "CySEC, ASIC, FSCA, IFSC", type: "Hybrid", platforms: "MT4 / MT5", highlight: "เลเวอเรจสูงถึง 1:3000 โปรโมชันจัดเต็ม", pros: ["เลเวอเรจสูงมาก", "โบนัสและกิจกรรมเยอะ"], cons: ["สเปรดสูงในบางบัญชี"] },
  { rank: 9, name: "XM", slug: "xm", rating: 5, leverage: "1:1000", minDeposit: "$5", regulation: "CySEC, ASIC, IFSC, DFSA", type: "Hybrid", platforms: "MT4 / MT5", highlight: "มือใหม่ยอดนิยม บัญชี Micro โบนัสเปิดบัญชี ซัพพอร์ตไทย", pros: ["เปิดบัญชีง่าย มีซัพพอร์ตภาษาไทย", "บัญชี Micro ทุนน้อย", "สัมมนา/คอนเทนต์สอนเยอะ"], cons: ["สเปรดสูงกว่าบัญชี ECN"] },
  { rank: 10, name: "Doo Prime", slug: "doo-prime", rating: 5, leverage: "1:1000", minDeposit: "$100", regulation: "FCA, ASIC, MAS, FSC", type: "Hybrid / ECN", platforms: "MT4 / MT5", highlight: "กลุ่มการเงินใหญ่ มีบัญชี ECN/Cent ครบ Copy Trade", pros: ["เครือบริษัทการเงินใหญ่", "มีทั้ง ECN และ Cent"], cons: ["เป็นที่รู้จักในไทยน้อยกว่าเจ้าใหญ่"] },
  { rank: 11, name: "OctaFX", slug: "octafx", rating: 3, leverage: "1:1000", minDeposit: "$25", regulation: "CySEC, FSCA, SVG", type: "Hybrid", platforms: "MT4 / MT5 / cTrader", highlight: "สเปรดต่ำ Copy Trade ในแอป ฝาก-ถอนสะดวก", pros: ["Copy Trade ในแอปใช้ง่าย", "ไม่มีค่าคอมในบัญชีพื้นฐาน"], cons: ["ใบอนุญาตหลักอยู่ offshore"] },
  { rank: 12, name: "IUX Markets", slug: "iux", rating: 3, leverage: "1:3000", minDeposit: "$1", regulation: "FSCA, SVG", type: "Hybrid", platforms: "MT4 / MT5", highlight: "ทุนเริ่มต้นต่ำมาก เลเวอเรจสูง กำลังมาแรงในไทย", pros: ["เริ่มต้นทุนน้อย", "อินเทอร์เฟซภาษาไทยดี"], cons: ["ใบอนุญาต offshore เป็นหลัก"] },
  { rank: 13, name: "XTB", slug: "xtb", rating: 3, leverage: "1:500", minDeposit: "ไม่กำหนด", regulation: "FCA, CySEC, KNF", type: "A-book", platforms: "xStation 5", highlight: "แพลตฟอร์ม xStation ของตัวเองใช้ดี จดทะเบียนในตลาดหุ้น", pros: ["บริษัทจดทะเบียนในตลาดหลักทรัพย์", "แพลตฟอร์มของตัวเองเสถียร"], cons: ["ไม่รองรับ MT4/MT5"] },
  { rank: 14, name: "Weltrade", slug: "weltrade", rating: 2, leverage: "1:2000", minDeposit: "$25", regulation: "IFSC, SVG", type: "Hybrid", platforms: "MT4 / MT5", highlight: "เลเวอเรจสูง โปรโมชันเยอะ เหมาะสายทุนน้อย", pros: ["เลเวอเรจสูง", "โบนัสเยอะ"], cons: ["ใบอนุญาต offshore"] },
  { rank: 15, name: "Markets4you", slug: "markets4you", rating: 2, leverage: "1:4000", minDeposit: "ไม่กำหนด", regulation: "SVG, FSC", type: "Hybrid", platforms: "MT4 / MT5", highlight: "เลเวอเรจสูงสุด 1:4000 มีบัญชี Cent", pros: ["เลเวอเรจสูงมาก", "บัญชี Cent ทุนน้อย"], cons: ["กำกับดูแล offshore"] },
  { rank: 16, name: "RoboForex", slug: "roboforex", rating: 3, leverage: "1:2000", minDeposit: "$10", regulation: "FSC Belize", type: "Hybrid / ECN", platforms: "MT4 / MT5 / cTrader", highlight: "เครื่องมือเทรดครบ มี R StocksTrader โปรโมชันเยอะ", pros: ["เครื่องมือและบัญชีหลากหลาย", "โปรโมชันเยอะ"], cons: ["ใบอนุญาตหลัก offshore"] },
  { rank: 17, name: "VT Markets", slug: "vt-markets", rating: 3, leverage: "1:1000", minDeposit: "$100", regulation: "ASIC, FSCA, SVG", type: "Hybrid", platforms: "MT4 / MT5 / TradingView", highlight: "สเปรดแข่งขันได้ รองรับ TradingView กำลังโต", pros: ["รองรับ TradingView", "ค่าธรรมเนียมแข่งขันได้"], cons: ["เป็นที่รู้จักในไทยปานกลาง"] },
  { rank: 18, name: "Vantage", slug: "vantage", rating: 3, leverage: "1:2000", minDeposit: "$50", regulation: "ASIC, FCA, CIMA", type: "Hybrid / ECN", platforms: "MT4 / MT5 / TradingView", highlight: "บัญชี Raw ECN สเปรดต่ำ มีกำกับดูแล Tier-1", pros: ["บัญชี ECN สเปรดต่ำ", "มีใบอนุญาต ASIC/FCA"], cons: ["บางบัญชีอยู่ภายใต้ offshore"] },
  { rank: 19, name: "CXM Direct", slug: "cxm-direct", rating: 2, leverage: "1:2000", minDeposit: "$50", regulation: "FCA (appointed), SVG", type: "Hybrid", platforms: "MT4 / MT5", highlight: "เลเวอเรจสูง ฝาก-ถอนสะดวก เหมาะทุนน้อย", pros: ["เลเวอเรจสูง", "เปิดบัญชีง่าย"], cons: ["โครงสร้างใบอนุญาตซับซ้อน"] },
  { rank: 20, name: "ThinkMarkets", slug: "thinkmarkets", rating: 4, leverage: "1:500", minDeposit: "ไม่กำหนด", regulation: "FCA, ASIC, CySEC", type: "A-book", platforms: "MT4 / MT5 / ThinkTrader", highlight: "กำกับดูแลแน่น แพลตฟอร์ม ThinkTrader ของตัวเองดี", pros: ["ใบอนุญาต Tier-1", "แพลตฟอร์มของตัวเองใช้ง่าย"], cons: ["โปรโมชันน้อย"] },
  { rank: 21, name: "ATFX", slug: "atfx", rating: 4, leverage: "1:400", minDeposit: "$100", regulation: "FCA, CySEC, FSCA", type: "Hybrid", platforms: "MT4 / MT5", highlight: "โบรกที่กำกับดูแลดี เหมาะนักลงทุนเน้นความปลอดภัย", pros: ["กำกับดูแลหลายประเทศ", "บริการลูกค้าดี"], cons: ["เลเวอเรจต่ำกว่าโบรก offshore"] },
  { rank: 22, name: "Swissquote", slug: "swissquote", rating: 5, leverage: "1:400", minDeposit: "$1,000", regulation: "FINMA, FCA, MAS", type: "A-book", platforms: "MT4 / MT5 / Advanced Trader", highlight: "ธนาคารสวิส ความปลอดภัยสูงสุด เหมาะทุนใหญ่", pros: ["ธนาคารกำกับโดย FINMA ปลอดภัยสูง", "สินทรัพย์ให้เทรดหลากหลาย"], cons: ["เงินฝากขั้นต่ำสูง ค่าธรรมเนียมสูง"] },
  { rank: 23, name: "Saxo Bank", slug: "saxo-bank", rating: 5, leverage: "1:30", minDeposit: "ไม่กำหนด", regulation: "FINMA, FCA, MAS, DFSA", type: "A-book", platforms: "SaxoTraderGO / PRO", highlight: "ธนาคารเพื่อการลงทุน สินทรัพย์ครบที่สุด เหมาะมืออาชีพ", pros: ["ธนาคารระดับโลก น่าเชื่อถือสูงสุด", "สินทรัพย์ให้เทรดหลากหลายมาก"], cons: ["เลเวอเรจต่ำ (กฎ EU)", "เหมาะทุนสูง"] },
  { rank: 24, name: "FP Markets", slug: "fp-markets", rating: 4, leverage: "1:500", minDeposit: "$100", regulation: "ASIC, CySEC", type: "A-book / ECN", platforms: "MT4 / MT5 / cTrader / TradingView", highlight: "ECN สเปรดต่ำ กำกับดูแลดี เหมาะรัน EA", pros: ["ECN สเปรดต่ำ", "กำกับดูแล ASIC/CySEC"], cons: ["โปรโมชันน้อย"] },
  { rank: 25, name: "Forex.com", slug: "forex-com", rating: 4, leverage: "1:200", minDeposit: "$100", regulation: "CFTC, NFA, FCA", type: "Hybrid", platforms: "MT4 / MT5 / WebTrader", highlight: "โบรกใหญ่ระดับโลก เครือ StoneX กำกับดูแล US", pros: ["เครือบริษัทมหาชน น่าเชื่อถือ", "เครื่องมือวิเคราะห์ครบ"], cons: ["เลเวอเรจจำกัดตามกฎ"] },
  { rank: 26, name: "Interactive Brokers", slug: "interactive-brokers", rating: 5, leverage: "1:50", minDeposit: "ไม่กำหนด", regulation: "SEC, FCA, ASIC", type: "A-book", platforms: "TWS / IBKR", highlight: "บริษัทมหาชน US สินทรัพย์ครบ ค่าธรรมเนียมต่ำ เหมาะลงทุนระยะยาว", pros: ["บริษัทจดทะเบียนสหรัฐฯ น่าเชื่อถือสูง", "ค่าธรรมเนียมต่ำ สินทรัพย์ครบ"], cons: ["เลเวอเรจต่ำ แพลตฟอร์มซับซ้อนสำหรับมือใหม่"] },
  { rank: 27, name: "Admirals", slug: "admirals", rating: 4, leverage: "1:1000", minDeposit: "$1", regulation: "FCA, CySEC, ASIC, EFSA", type: "Hybrid", platforms: "MT4 / MT5", highlight: "กำกับดูแลแน่น เครื่องมือ MetaTrader เสริมครบ", pros: ["ใบอนุญาต Tier-1 หลายใบ", "เครื่องมือเสริม MT4/MT5 เยอะ"], cons: ["บัญชีพื้นฐานสเปรดปานกลาง"] },
  { rank: 28, name: "MultiBank", slug: "multibank", rating: 3, leverage: "1:500", minDeposit: "$50", regulation: "ASIC, CIMA, BaFin", type: "Hybrid", platforms: "MT4 / MT5", highlight: "กลุ่มการเงินระดับโลก กำกับดูแลหลายประเทศ", pros: ["กำกับดูแลหลายประเทศ", "สภาพคล่องสูง"], cons: ["เป็นที่รู้จักในไทยปานกลาง"] },
  { rank: 29, name: "Axi", slug: "axi", rating: 4, leverage: "1:1000", minDeposit: "ไม่กำหนด", regulation: "ASIC, FCA, DFSA", type: "A-book", platforms: "MT4 / MT5", highlight: "A-book ออสเตรเลีย สเปรดต่ำ มี Copy Trade", pros: ["A-book กำกับ ASIC/FCA", "ไม่มีเงินฝากขั้นต่ำ"], cons: ["สินทรัพย์ให้เทรดน้อยกว่าเจ้าใหญ่"] },
  { rank: 30, name: "FXOpen", slug: "fxopen", rating: 4, leverage: "1:500", minDeposit: "$10", regulation: "FCA, ASIC, CySEC", type: "ECN", platforms: "MT4 / MT5 / TickTrader", highlight: "ECN เก่าแก่ สเปรดต่ำ กำกับดูแลดี", pros: ["ECN สเปรดต่ำ", "ใบอนุญาต FCA/ASIC"], cons: ["แบรนด์เงียบกว่าเจ้าใหญ่"] },
  { rank: 31, name: "HTFX", slug: "htfx", rating: 3, leverage: "1:500", minDeposit: "$50", regulation: "FSA, offshore", type: "Hybrid", platforms: "MT4 / MT5", highlight: "โบรกกำลังโต โปรโมชันเยอะ เน้นตลาดเอเชีย", pros: ["โปรโมชันเยอะ", "ซัพพอร์ตเอเชีย"], cons: ["ใบอนุญาต offshore"] },
  { rank: 32, name: "FXCM", slug: "fxcm", rating: 4, leverage: "1:1000", minDeposit: "$50", regulation: "FCA, ASIC", type: "Hybrid", platforms: "MT4 / Trading Station", highlight: "โบรกเก่าแก่ระดับโลก เครื่องมือวิเคราะห์ครบ", pros: ["ชื่อเสียงยาวนาน", "เครื่องมือวิเคราะห์ดี"], cons: ["เคยมีประวัติด้านกฎระเบียบในอดีต"] },
  { rank: 33, name: "AvaTrade", slug: "avatrade", rating: 3, leverage: "1:400", minDeposit: "$100", regulation: "CBI, ASIC, FSCA, FSA", type: "Hybrid", platforms: "MT4 / MT5 / AvaTradeGO", highlight: "กำกับดูแลหลายประเทศ มีแอปเทรดของตัวเอง", pros: ["กำกับดูแลหลายทวีป", "แพลตฟอร์มหลากหลาย"], cons: ["มีค่าธรรมเนียม inactivity"] },
  { rank: 34, name: "TMGM", slug: "tmgm", rating: 3, leverage: "1:1000", minDeposit: "$100", regulation: "ASIC, VFSC", type: "Hybrid / ECN", platforms: "MT4 / MT5", highlight: "โบรกออสเตรเลีย สเปรดต่ำ เน้นตลาดเอเชีย", pros: ["บัญชี ECN สเปรดต่ำ", "กำกับ ASIC"], cons: ["บางบัญชีอยู่ใต้ offshore"] },
  { rank: 35, name: "Capital.com", slug: "capital-com", rating: 4, leverage: "1:300", minDeposit: "$20", regulation: "FCA, CySEC, ASIC, SCB", type: "A-book", platforms: "เว็บ/แอปของตัวเอง / MT4", highlight: "แพลตฟอร์มใช้ง่าย มี AI ช่วยวิเคราะห์ เหมาะมือใหม่", pros: ["แพลตฟอร์มทันสมัย ใช้ง่าย", "กำกับดูแล Tier-1"], cons: ["เน้น CFD ไม่ใช่ MT เต็มรูปแบบ"] },
  { rank: 36, name: "InstaForex", slug: "instaforex", rating: 3, leverage: "1:1000", minDeposit: "$1", regulation: "FSC, CySEC", type: "Hybrid", platforms: "MT4 / MT5", highlight: "โบรกเก่าแก่ ทุนเริ่มต้นต่ำ โปรโมชันเยอะ", pros: ["เริ่มต้นทุนน้อย", "โปรโมชันเยอะ"], cons: ["สเปรดค่อนข้างสูง"] },
  { rank: 37, name: "Markets.com", slug: "markets-com", rating: 4, leverage: "1:300", minDeposit: "$100", regulation: "CySEC, FCA, ASIC, FSCA", type: "A-book", platforms: "เว็บ/แอป / MT4 / MT5", highlight: "เครือ Finalto กำกับดูแลดี เครื่องมือวิเคราะห์ครบ", pros: ["กำกับดูแลหลายประเทศ", "เครื่องมือวิเคราะห์ในตัว"], cons: ["เน้น CFD"] },
  { rank: 38, name: "Fxview", slug: "fxview", rating: 3, leverage: "1:500", minDeposit: "ไม่กำหนด", regulation: "CySEC, FSC", type: "ECN", platforms: "MT4 / MT5 / cTrader", highlight: "ค่าธรรมเนียมต่ำ ECN โปร่งใส", pros: ["ค่าธรรมเนียมต่ำ", "บัญชี ECN"], cons: ["แบรนด์เล็กในไทย"] },
  { rank: 39, name: "CMC Markets", slug: "cmc-markets", rating: 4, leverage: "1:500", minDeposit: "ไม่กำหนด", regulation: "FCA, ASIC", type: "A-book", platforms: "Next Generation / MT4", highlight: "บริษัทมหาชน UK สินทรัพย์ครบ แพลตฟอร์มทรงพลัง", pros: ["บริษัทจดทะเบียน UK น่าเชื่อถือ", "สินทรัพย์และกราฟครบ"], cons: ["เลเวอเรจจำกัดตามกฎ"] },
  { rank: 40, name: "EBC Financial", slug: "ebc-financial", rating: 3, leverage: "1:500", minDeposit: "$50", regulation: "FCA, ASIC, CIMA", type: "A-book / ECN", platforms: "MT4 / MT5", highlight: "โบรกกำลังโต กำกับดูแลดี สเปรดแข่งขันได้", pros: ["กำกับดูแล FCA/ASIC", "สเปรดต่ำ"], cons: ["ยังใหม่ในตลาดไทย"] },
  { rank: 41, name: "FXGT", slug: "fxgt", rating: 3, leverage: "1:5000", minDeposit: "$5", regulation: "FSCA, FSC", type: "Hybrid", platforms: "MT4 / MT5", highlight: "เลเวอเรจสูงสุด 1:5000 เทรดทั้ง Forex และคริปโต", pros: ["เลเวอเรจสูงมาก", "รองรับคริปโตหลากหลาย"], cons: ["ใบอนุญาต offshore เป็นหลัก"] },
  { rank: 42, name: "GO Markets", slug: "go-markets", rating: 3, leverage: "1:500", minDeposit: "$200", regulation: "ASIC, CySEC, FSC", type: "Hybrid / ECN", platforms: "MT4 / MT5 / TradingView", highlight: "โบรกออสเตรเลียเก่าแก่ ECN สเปรดต่ำ", pros: ["กำกับ ASIC", "บัญชี ECN"], cons: ["เงินฝากขั้นต่ำ $200"] },
  { rank: 43, name: "JustMarkets", slug: "justmarkets", rating: 3, leverage: "1:3000", minDeposit: "$1", regulation: "FSCA, FSC, CySEC", type: "Hybrid", platforms: "MT4 / MT5", highlight: "ทุนเริ่มต้นต่ำ เลเวอเรจสูง กำลังมาในเอเชีย", pros: ["เริ่มต้นทุนน้อย", "เลเวอเรจสูง"], cons: ["ใบอนุญาตหลัก offshore"] },
  { rank: 44, name: "Dukascopy", slug: "dukascopy", rating: 3, leverage: "1:200", minDeposit: "$100", regulation: "FINMA, JFSA", type: "A-book / ECN", platforms: "JForex / MT4", highlight: "ธนาคารสวิส ECN โปร่งใส เหมาะมืออาชีพ", pros: ["ธนาคารกำกับ FINMA", "ECN โปร่งใส"], cons: ["แพลตฟอร์มซับซ้อน"] },
  { rank: 45, name: "IronFX", slug: "ironfx", rating: 2, leverage: "1:1000", minDeposit: "$50", regulation: "CySEC, FSCA", type: "Hybrid", platforms: "MT4", highlight: "โบรกเก่าแก่ บัญชีหลากหลาย โปรโมชันเยอะ", pros: ["บัญชีให้เลือกเยอะ", "โปรโมชันเยอะ"], cons: ["เคยมีประวัติเรื่องการถอนในอดีต"] },
  { rank: 46, name: "ActivTrades", slug: "activtrades", rating: 3, leverage: "1:400", minDeposit: "ไม่กำหนด", regulation: "FCA, SCB, CSSF", type: "A-book", platforms: "MT4 / MT5 / ActivTrader", highlight: "โบรก UK กำกับดูแลดี มีประกันเงินทุนเสริม", pros: ["กำกับ FCA มีประกันเสริม", "แพลตฟอร์มของตัวเองดี"], cons: ["โปรโมชันน้อย"] },
  { rank: 47, name: "easyMarkets", slug: "easymarkets", rating: 3, leverage: "1:400", minDeposit: "$25", regulation: "ASIC, CySEC, FSC", type: "Hybrid", platforms: "เว็บ/แอป / MT4 / MT5", highlight: "เด่นเรื่องฟีเจอร์ปิดความเสี่ยง (Freeze Rate / dealCancellation)", pros: ["ฟีเจอร์จัดการความเสี่ยงเด่น", "สเปรดคงที่ให้เลือก"], cons: ["สเปรดคงที่สูงกว่า ECN"] },
  { rank: 48, name: "Doto", slug: "doto", rating: 3, leverage: "1:500", minDeposit: "$10", regulation: "CySEC, FSA", type: "Hybrid", platforms: "MT4 / MT5", highlight: "โบรกใหม่ อินเทอร์เฟซทันสมัย ฝาก-ถอนสะดวก", pros: ["แพลตฟอร์มทันสมัย", "เปิดบัญชีง่าย"], cons: ["ยังใหม่ ประวัติสั้น"] },
  { rank: 49, name: "Afterprime", slug: "afterprime", rating: 3, leverage: "1:1000", minDeposit: "$100", regulation: "FCA (appointed), VFSC", type: "ECN", platforms: "MT4 / MT5 / cTrader", highlight: "ECN โปร่งใส เปิดเผยข้อมูลราคาจริง เหมาะเทรดเดอร์จริงจัง", pros: ["ECN โปร่งใสมาก", "ค่าคอมต่ำ"], cons: ["แบรนด์เล็ก รู้จักน้อย"] },
  { rank: 50, name: "Zero Markets", slug: "zero-markets", rating: 2, leverage: "1:500", minDeposit: "$50", regulation: "ASIC, VFSC", type: "Hybrid", platforms: "MT4 / MT5", highlight: "โบรกออสเตรเลีย สเปรดต่ำ เน้นตลาดเอเชีย", pros: ["บัญชี Raw สเปรดต่ำ", "ฝาก-ถอนสะดวก"], cons: ["บางบัญชีอยู่ใต้ offshore"] },
];
